"""Initial migration

Revision ID: 176a6e39d071
Revises: 
Create Date: 2024-09-21 07:54:42.680167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176a6e39d071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    # ### end Alembic commands ###
