"""Initial migration

Revision ID: 51378ab75dbf
Revises: 176a6e39d071
Create Date: 2024-09-21 08:53:54.315622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51378ab75dbf'
down_revision = '176a6e39d071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
